-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "episode_id" DROP NOT NULL,
ALTER COLUMN "producer" DROP NOT NULL,
ALTER COLUMN "release_date" DROP NOT NULL,
ALTER COLUMN "characters" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "planets" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "starships" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "vehicles" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "species" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "created" DROP NOT NULL,
ALTER COLUMN "edited" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL;
